
# ----------------------------------------------------
# 2. MASTER MAPPING (YOUR FULL LIST)
# ----------------------------------------------------
MASTER_MAP = {
    "20MICRONS.NS": {"Name": "20 Microns Ltd.", "Sector": "Chemicals - Specialty"},
    "AARTIIND.NS": {"Name": "Aarti Industries", "Sector": "Chemicals - Specialty"},
    "ABB.NS": {"Name": "ABB India", "Sector": "Electrical Equipment - Industrial"},
    "ACC.NS": {"Name": "ACC", "Sector": "Cement"},
    "ACMESOLAR.NS": {"Name": "Acme Solar Holdings", "Sector": "Renewable Energy"},
    "ADANIENSOL.NS": {"Name": "Adani Energy Solutions", "Sector": "Power Transmission & Distribution"},
    "ADANIENT.NS": {"Name": "Adani Enterprises Ltd.", "Sector": "Conglomerate"},
    "ADANIGREEN.NS": {"Name": "Adani Green Energy Ltd.", "Sector": "Renewable Energy"},
    "ADANIPORTS.NS": {"Name": "Adani Ports & Special Economic Zone Ltd.", "Sector": "Infrastructure - Ports"},
    "ADANIPOWER.NS": {"Name": "Adani Power Ltd.", "Sector": "Power Generation"},
    "ATGL.NS": {"Name": "Adani Total Gas", "Sector": "Gas Distribution"},
    "ABCAPITAL.NS": {"Name": "Aditya Birla Capital", "Sector": "Financial Services - Holding"},
    "ABFRL.NS": {"Name": "Aditya Birla Fashion and Retail Ltd.", "Sector": "Retail - Apparel"},
    "ABREL.NS": {"Name": "Aditya Birla Real Estates", "Sector": "Real Estate"},
    "AFCONS.NS": {"Name": "Afcons Infrastructure Ltd.", "Sector": "Construction & Infrastructure"},
    "AHLUCONT.NS": {"Name": "Ahluwalia Contracts (India) Ltd.", "Sector": "Construction"},
    "ALKYLAMINE.NS": {"Name": "Alkyl Amines Chemicals Ltd.", "Sector": "Chemicals - Specialty"},
    "ABDL.NS": {"Name": "Allied Blenders & Distillers", "Sector": "FMCG - Alcoholic Beverages"},
    "ADSL.NS": {"Name": "Allied Digital", "Sector": "IT Services"},
    "ALMONDZ.BO": {"Name": "Almondz Global", "Sector": "Financial Services - Capital Markets"},
    "ARE&M.NS": {"Name": "Amara Raja Energy & Mobility", "Sector": "Auto Ancillaries - Batteries"},
    "AMBER.NS": {"Name": "Amber Enterprises India Ltd", "Sector": "Consumer Durables - EMS"},
    "AMBUJACEM.NS": {"Name": "Ambuja Cements", "Sector": "Cement"},
    "ANANTRAJ.NS": {"Name": "Anant Raj", "Sector": "Real Estate"},
    "ACL.BO": {"Name": "Andhra Cements", "Sector": "Cement"},
    "ANGELONE.NS": {"Name": "Angel One", "Sector": "Financial Services - Stockbroking"},
    "APARINDS.NS": {"Name": "Apar Industries", "Sector": "Capital Goods"},
    "APLAPOLLO.NS": {"Name": "APL Apollo Tubes", "Sector": "Metals - Steel Pipes"},
    "APOLLOHOSP.NS": {"Name": "Apollo Hospitals Enterprise Ltd.", "Sector": "Healthcare Services"},
    "APOLLO.NS": {"Name": "Apollo Micro Systems", "Sector": "Defence - Electronic Systems"},
    "APOLLOPIPE.NS": {"Name": "Apollo Pipes", "Sector": "Plastics & Pipes"},
    "APOLLOTYRE.NS": {"Name": "Apollo Tyres", "Sector": "Auto Ancillaries"},
    "ARVINDFASN.NS": {"Name": "Arvind Fashions Ltd.", "Sector": "Retail - Apparel"},
    "ARVIND.NS": {"Name": "Arvind Ltd", "Sector": "Textiles"},
    "ASAHIINDIA.NS": {"Name": "Asahi India Glass Ltd.", "Sector": "Consumer Durables - Glass"},
    "ASHOKLEY.NS": {"Name": "Ashok Leyland", "Sector": "Auto"},
    "ASHOKA.NS": {"Name": "Ashoka Buildcon", "Sector": "Construction & Infrastructure"},
    "ASIANENE.NS": {"Name": "Asian Energy Services", "Sector": "Oil & Gas - Services"},
    "ASIANHOTNR.NS": {"Name": "Asian Hotels (North) Ltd.", "Sector": "Hospitality"},
    "ASIANPAINT.NS": {"Name": "Asian Paints", "Sector": "Paints & Coatings"},
    "ASMTEC.BO": {"Name": "ASM Technologies Ltd", "Sector": "IT Services - Semiconductor"},
    "ASTRAMICRO.NS": {"Name": "Astra Microwave Products Ltd", "Sector": "Defence & Aerospace"},
    "ASTRAL.NS": {"Name": "Astral Ltd", "Sector": "Plastics & Pipes"},
    "ATULAUTO.NS": {"Name": "Atul Auto", "Sector": "Auto"},
    "ATUL.NS": {"Name": "Atul Ltd", "Sector": "Chemicals - Specialty"},
    "AURIONPRO.NS": {"Name": "Aurionpro Solutions", "Sector": "IT Services - Fintech"},
    "AUROPHARMA.NS": {"Name": "Aurobindo Pharma", "Sector": "Pharmaceuticals"},
    "AUTOIND.NS": {"Name": "Autoline Industries", "Sector": "Auto Ancillaries"},
    "AVANTEL.NS": {"Name": "Avantel Ltd.", "Sector": "Communications Equipment"},
    "AVANTIFEED.NS": {"Name": "Avanti Feeds", "Sector": "FMCG - Aquaculture"},
    "AWFIS.NS": {"Name": "AWFIS", "Sector": "Real Estate - Services"},
    "AXISBANK.NS": {"Name": "Axis Bank", "Sector": "Financial Services - Banking"},
    "BAJAJ-AUTO.NS": {"Name": "Bajaj Auto", "Sector": "Auto"},
    "BAJAJCON.NS": {"Name": "Bajaj Consumer Care Ltd.", "Sector": "FMCG - Personal Care"},
    "BAJAJFINSV.NS": {"Name": "Bajaj Finserv", "Sector": "Financial Services - NBFC"},
    "BAJFINANCE.NS": {"Name": "Bajaj Finance", "Sector": "Financial Services - NBFC"},
    "BAJAJST.BO": {"Name": "Bajaj Steel Inds. Ltd.", "Sector": "Metals - Steel"},
    "BALAMINES.NS": {"Name": "Balaji Amines", "Sector": "Chemicals - Specialty"},
    "BALRAMCHIN.NS": {"Name": "Balrampur Chini Mills Ltd.", "Sector": "Sugar"},
    "BANCOINDIA.NS": {"Name": "Banco Products (India) Ltd.", "Sector": "Auto Ancillaries"},
    "BANDHANBNK.NS": {"Name": "Bandhan Bank", "Sector": "Financial Services - Banking"},
    "BANKBARODA.NS": {"Name": "Bank of Baroda", "Sector": "Financial Services - Banking"},
    "BEEKAY.BO": {"Name": "Beekay Steel Industries Ltd.", "Sector": "Metals - Steel"},
    "BEL.NS": {"Name": "BEL (Bharat Electronics)", "Sector": "Defence & Aerospace"},
    "BEML.NS": {"Name": "BEML", "Sector": "Defence - Heavy Engineering"},
    "BERGEPAINT.NS": {"Name": "Berger Paints", "Sector": "Paints & Coatings"},
    "BDL.NS": {"Name": "Bharat Dynamics", "Sector": "Defence & Aerospace"},
    "BHARATFORG.NS": {"Name": "Bharat Forge Ltd", "Sector": "Defence - Auto Ancillaries"},
    "BHARTIARTL.NS": {"Name": "Bharti Airtel Ltd.", "Sector": "Telecommunications"},
    "BHARTIHEXA.NS": {"Name": "Bharti Hexacom", "Sector": "Telecommunications"},
    "BHEL.NS": {"Name": "BHEL", "Sector": "Heavy Electrical Equipment"},
    "BIOCON.NS": {"Name": "Biocon", "Sector": "Pharmaceuticals - Biotech"},
    "BIRLACORPN.NS": {"Name": "Birla Corpn.", "Sector": "Cement"},
    "BSOFT.NS": {"Name": "Birlasoft Ltd", "Sector": "IT Services"},
    "BBOX.NS": {"Name": "Black Box Ltd.", "Sector": "IT Services - Networking"},
    "BMW.NS": {"Name": "BMW Industries Ltd.", "Sector": "Metals - Steel"},
    "BOROLTD.NS": {"Name": "Borosil Ltd", "Sector": "Consumer Durables - Glass"},
    "BORORENEW.NS": {"Name": "Borosil Renewables Ltd.", "Sector": "Renewable Energy"},
    "BRIGADE.NS": {"Name": "Brigade Enterprises", "Sector": "Real Estate"},
    "BIRET.NS": {"Name": "Brookfield India Real Estate Trust", "Sector": "Real Estate - REIT"},
    "BSE.NS": {"Name": "BSE Ltd", "Sector": "Financial Services - Exchange"},
    "MAPMYINDIA.NS": {"Name": "C.E. Info Systems Ltd.", "Sector": "IT Services - GIS Mapping"},
    "CAMS.NS": {"Name": "CAMS", "Sector": "Financial Services - AMC Services"},
    "CAPLIPOINT.NS": {"Name": "Caplin Point Laboratories", "Sector": "Pharmaceuticals"},
    "CARRARO.NS": {"Name": "Carraro India Ltd.", "Sector": "Auto Ancillaries"},
    "CARYSIL.NS": {"Name": "Carysil", "Sector": "Consumer Durables"},
    "CDSL.NS": {"Name": "CDSL", "Sector": "Financial Services - Depository"},
    "CERA.NS": {"Name": "Cera Sanitaryware Ltd.", "Sector": "Consumer Durables"},
    "CFF.BO": {"Name": "CFF Fluid Control Ltd", "Sector": "Defence"},
    "CGPOWER.NS": {"Name": "CG Power and Industrial Solutions", "Sector": "Electrical Equipment - Semiconductor"},
    "CHALET.NS": {"Name": "Chalet Hotels", "Sector": "Hospitality"},
    "CHAMBLFERT.NS": {"Name": "Chambal Fertilisers & Chemicals Ltd.", "Sector": "Fertilizers"},
    "CHEMPLASTS.NS": {"Name": "Chemplast Sanmar Ltd", "Sector": "Chemicals - Specialty"},
    "CHOLAHLDNG.NS": {"Name": "Cholamandalam Financial Holdings Ltd.", "Sector": "Financial Services - Holding"},
    "CHOLAFIN.NS": {"Name": "Cholamandalam Investment & Finance Company Ltd.", "Sector": "Financial Services - NBFC"},
    "CIEINDIA.NS": {"Name": "CIE Automotive India Ltd.", "Sector": "Auto Ancillaries"},
    "CIPLA.NS": {"Name": "Cipla", "Sector": "Pharmaceuticals"},
    "CUB.NS": {"Name": "City Union Bank", "Sector": "Financial Services - Banking"},
    "COALINDIA.NS": {"Name": "Coal India", "Sector": "Mining"},
    "COCHINSHIP.NS": {"Name": "Cochin Shipyard", "Sector": "Defence - Shipbuilding"},
    "COFORGE.NS": {"Name": "Coforge", "Sector": "IT Services"},
    "CONCOR.NS": {"Name": "Container Corporation of India Ltd.", "Sector": "Logistics"},
    "COROMANDEL.NS": {"Name": "Coromandel International", "Sector": "Fertilizers - Chemicals"},
    "CRAFTSMAN.NS": {"Name": "Craftsman Automation Ltd.", "Sector": "Capital Goods - Auto Ancillaries"},
    "CYIENTDLM.NS": {"Name": "Cyient DLM", "Sector": "EMS (Electronics Manufacturing)"},
    "DPWIRES.NS": {"Name": "D P Wires", "Sector": "Metals - Steel"},
    "DABUR.NS": {"Name": "Dabur India", "Sector": "FMCG - Health"},
    "DATAPATTNS.NS": {"Name": "Data Patterns (India) Ltd.", "Sector": "Defence & Aerospace"},
    "DAVANGERE.NS": {"Name": "Davangere Sugar Company Ltd.", "Sector": "Sugar"},
    "DCXINDIA.BO": {"Name": "DCX Systems Limited", "Sector": "EMS (Electronics Manufacturing)"},
    "DEEDEV.NS": {"Name": "Dee Development Engineers", "Sector": "Capital Goods - Engineering"},
    "DEEPAKFERT.NS": {"Name": "Deepak Fertilisers & Petrochemicals Corporation Ltd.", "Sector": "Chemicals - Fertilizers"},
    "DEEPAKNTR.NS": {"Name": "Deepak Nitrate", "Sector": "Chemicals - Specialty"},
    "DELHIVERY.NS": {"Name": "Delhivery", "Sector": "Logistics"},
    "DEVYANI.NS": {"Name": "Devyani International", "Sector": "Retail - QSR"},
    "DHABRIYA.BO": {"Name": "Dhabriya Polywood Ltd.", "Sector": "Plastics & Polymers"},
    "DHAMPURSUG.NS": {"Name": "Dhampur Sugar Mills Ltd.", "Sector": "Sugar"},
    "DBL.NS": {"Name": "Dilip Buildcon Ltd.", "Sector": "Construction & Infrastructure"},
    "DIVISLAB.NS": {"Name": "Divi's Laboratories Ltd.", "Sector": "Pharmaceuticals - APIs"},
    "DIXON.NS": {"Name": "Dixon Technologies (India) Ltd.", "Sector": "EMS (Electronics Manufacturing)"},
    "DLF.NS": {"Name": "DLF", "Sector": "Real Estate"},
    "DUCON.NS": {"Name": "Ducon Infratechnologies Ltd", "Sector": "Environmental Services"},
    "DYNAMATECH.NS": {"Name": "Dynamatic Technologies Ltd.", "Sector": "Defence - Auto Ancillaries"},
    "E2E.NS": {"Name": "E2E Networks Ltd", "Sector": "IT Services - Cloud"},
    "EASEMYTRIP.NS": {"Name": "Easy Trip Planners", "Sector": "Travel Services"},
    "EICHERMOT.NS": {"Name": "Eicher Motors", "Sector": "Auto"},
    "EIHOTEL.NS": {"Name": "EIH Ltd", "Sector": "Hospitality"},
    "EKI.BO": {"Name": "EKI Energy Services Ltd.", "Sector": "Environmental Services"},
    "EMAMILTD.NS": {"Name": "Emami Ltd", "Sector": "Consumer Goods"},
    "EMBASSY.NS": {"Name": "Embassy Office Parks REIT", "Sector": "Real Estate - REIT"},
    "EMKAY.NS": {"Name": "Emkay Global", "Sector": "Financial Services - Stockbroking"},
    "EMUDHRA.NS": {"Name": "eMudhra Ltd.", "Sector": "IT Services - Digital Security"},
    "IBREALEST.NS": {"Name": "Equinox India Developments", "Sector": "Real Estate"},
    "EQUITASBNK.NS": {"Name": "Equitas Small Finance Bank Ltd.", "Sector": "Financial Services - Banking"},
    "ESSARSHPNG.NS": {"Name": "Essar Shipping", "Sector": "Shipping"},
    "ETERNAL.NS": {"Name": "Eternal", "Sector": "FMCG - E-commerce"},
    "EVEREADY.NS": {"Name": "Eveready Industries India Ltd.", "Sector": "Consumer Durables"},
    "EKC.NS": {"Name": "Everest Kanto Cylinder", "Sector": "Capital Goods"},
    "EXPLEOSOL.NS": {"Name": "Expleo Solutions", "Sector": "IT Services"},
    "FAZE3Q.NS": {"Name": "Faze Three Ltd.", "Sector": "Textiles"},
    "FEDERALBNK.NS": {"Name": "Federal Bank", "Sector": "Financial Services - Banking"},
    "FERMENTA.NS": {"Name": "Fermenta Biotech Ltd.", "Sector": "Pharmaceuticals - Biotech"},
    "FIEMIND.NS": {"Name": "Fiem Industries", "Sector": "Auto Ancillaries"},
    "FINEORG.NS": {"Name": "Fine Organic", "Sector": "Chemicals - Specialty"},
    "FCL.NS": {"Name": "Fineotex Chemical Ltd.", "Sector": "Chemicals - Specialty"},
    "FINCABLES.NS": {"Name": "Finolex Cables", "Sector": "Capital Goods - Cables & Wires"},
    "FINPIPE.NS": {"Name": "Finolex Inds.", "Sector": "Plastics & Pipes"},
    "FIVESTAR.NS": {"Name": "Five Star Business Finance", "Sector": "Financial Services - NBFC"},
    "NYKAA.NS": {"Name": "FSN E Commerce Ventures (Nykaa)", "Sector": "Retail - E-commerce"},
    "GAIL.NS": {"Name": "GAIL (India)", "Sector": "Oil & Gas"},
    "GALXBRG.BO": {"Name": "Galaxy Bearings Ltd.", "Sector": "Auto Ancillaries - Industrial"},
    "GRSE.NS": {"Name": "Garden Reach Shipbuilders & Engineers Ltd.", "Sector": "Defence - Shipbuilding"},
    "GARUDA.NS": {"Name": "Garuda Construction", "Sector": "Real Estate"},
    "GLAND.NS": {"Name": "Gland Pharma", "Sector": "Pharmaceuticals"},
    "GLENMARK.NS": {"Name": "Glenmark Pharma.", "Sector": "Pharmaceuticals"},
    "GLOBUSSPR.NS": {"Name": "Globus Spirits", "Sector": "FMCG - Alcoholic Beverages"},
    "GMRP&UI.NS": {"Name": "GMR Power and Urban Infra", "Sector": "Infrastructure - Power"},
    "GPIL.NS": {"Name": "Godawari Power & Ispat Ltd.", "Sector": "Metals - Steel"},
    "GODREJAGRO.NS": {"Name": "Godrej Agrovet", "Sector": "FMCG - Agribusiness"},
    "GODREJCP.NS": {"Name": "Godrej Consumer Products Ltd.", "Sector": "FMCG - Personal Care"},
    "GODREJPROP.NS": {"Name": "Godrej Properties", "Sector": "Real Estate"},
    "GOKEX.NS": {"Name": "Gokaldas Exports", "Sector": "Textiles - Apparel"},
    "GRANULES.NS": {"Name": "Granules India Ltd.", "Sector": "Pharmaceuticals"},
    "GRAPHITE.NS": {"Name": "Graphite India", "Sector": "Metals - Graphite Electrodes"},
    "GRASIM.NS": {"Name": "Grasim Inds", "Sector": "Conglomerate"},
    "GREENLAM.NS": {"Name": "Greenlam Industries", "Sector": "Wood & Wood Products"},
    "GREENPANEL.NS": {"Name": "Greenpanel Inds.", "Sector": "Wood & Wood Products"},
    "GREENPLY.NS": {"Name": "Greenply Inds.", "Sector": "Wood & Wood Products"},
    "GTLINFRA.NS": {"Name": "GTL Infra.", "Sector": "Telecommunications - Tower Infra"},
    "FLUOROCHEM.NS": {"Name": "Gujarat Fluoroch", "Sector": "Chemicals - Specialty"},
    "GVKPIL.BO": {"Name": "GVK Power Infra.", "Sector": "Infrastructure - Power"},
    "HAL.NS": {"Name": "HAL (Hindustan Aeronautics Ltd.)", "Sector": "Defence & Aerospace"},
    "HATHWAY.NS": {"Name": "Hathway Cable & Datacom Ltd.", "Sector": "Telecommunications - Broadband"},
    "HAVELLS.NS": {"Name": "Havells India Ltd", "Sector": "Consumer Durables - Electrical Equipment"},
    "HBLPOWER.NS": {"Name": "HBL Power Systems Ltd", "Sector": "Electrical Equipment"},
    "HCLTECH.NS": {"Name": "HCL Technologies", "Sector": "IT Services"},
    "HDFCAMC.NS": {"Name": "HDFC Asset Management Company Ltd.", "Sector": "Financial Services - AMC"},
    "HDFCBANK.NS": {"Name": "HDFC Bank", "Sector": "Financial Services - Banking"},
    "HDFCLIFE.NS": {"Name": "HDFC Life Insurance Company Ltd.", "Sector": "Financial Services - Insurance"},
    "HEMIPROP.NS": {"Name": "Hemisphere Properties", "Sector": "Real Estate"},
    "HGINFRA.NS": {"Name": "HG Infra", "Sector": "Construction & Infrastructure"},
    "HITECH.NS": {"Name": "Hi-tech Pipes", "Sector": "Electrical Equipment"},
    "HIGHENE.BO": {"Name": "High Energy Batteries (India) Ltd", "Sector": "Metals - Steel Pipes"},
    "HIRECT.NS": {"Name": "Hind Rectifiers Ltd.", "Sector": "Defence"},
    "HINDALCO.NS": {"Name": "Hindalco", "Sector": "Electrical Equipment"},
    "HINDCOPPER.NS": {"Name": "Hindustan Copper", "Sector": "Metals - Non-ferrous"},
    "HINDPETRO.NS": {"Name": "Hindustan Petroleum Corporation Ltd.", "Sector": "Metals - Non-ferrous"},
    "HINDUNILVR.NS": {"Name": "Hindustan Unilever", "Sector": "Oil & Gas"},
    "HINDZINC.NS": {"Name": "Hindustan Zinc", "Sector": "FMCG - Consumer Goods"},
    "POWERINDIA.NS": {"Name": "Hitachi Energy India Ltd", "Sector": "Metals - Non-ferrous"},
    "HUDCO.NS": {"Name": "HUDCO", "Sector": "Financial Services - Housing Finance"},
    "ICICIBANK.NS": {"Name": "ICICI Bank", "Sector": "Financial Services - Banking"},
    "ICICIGI.NS": {"Name": "ICICI Lombard General Insurance Company Ltd.", "Sector": "Financial Services - Insurance"},
    "ICICIPRULI.NS": {"Name": "ICICI Prudential Life Insurance Company Ltd.", "Sector": "Financial Services - Insurance"},
    "IDFCFIRSTB.NS": {"Name": "IDFC First Bank", "Sector": "Financial Services - Banking"},
    "IEX.NS": {"Name": "IEX (Indian Energy Exchange)", "Sector": "Financial Services - Exchange"},
    "IFCI.NS": {"Name": "IFCI Ltd", "Sector": "Financial Services - NBFC"},
    "IIFL.NS": {"Name": "IIFL Finance", "Sector": "Financial Services - NBFC"},
    "INDIAGLYCO.NS": {"Name": "India Glycol", "Sector": "Chemicals - Specialty"},
    "IPL.NS": {"Name": "India Pesticides Limited", "Sector": "Chemicals - Agrochemicals"},
    "INDHOTEL.NS": {"Name": "Indian Hotels Company Ltd", "Sector": "Hospitality"},
    "INDIANHUME.NS": {"Name": "Indian Hume Pipe", "Sector": "Construction - Pipes"},
    "IOC.NS": {"Name": "Indian Oil Corporation Ltd.", "Sector": "Oil & Gas"},
    "IRCTC.NS": {"Name": "Indian Railway Catering & Tourism Corporation Ltd.", "Sector": "Tourism - Railway Services"},
    "IRFC.NS": {"Name": "Indian Railway Finance Corporation Ltd.", "Sector": "Financial Services - NBFC"},
    "IREDA.NS": {"Name": "Indian Renewable Energy Development Agency Ltd", "Sector": "Financial Services - NBFC"},
    "INDIGOPNTS.NS": {"Name": "Indigo Paints", "Sector": "Paints"},
    "INDUSTOWER.NS": {"Name": "Indus Towers", "Sector": "Telecommunications - Tower Infra"},
    "INDUSINDBK.NS": {"Name": "IndusInd Bank", "Sector": "Financial Services - Banking"},
    "INFY.NS": {"Name": "Infosys", "Sector": "IT Services"},
    "INOXGREEN.NS": {"Name": "Inox Green Energy Services Ltd.", "Sector": "Renewable Energy - Services"},
    "INOXWIND.NS": {"Name": "Inox Wind", "Sector": "Renewable Energy"},
    "INSECTICID.NS": {"Name": "Insecticides (India)", "Sector": "Chemicals - Agrochemicals"},
    "INDIGO.NS": {"Name": "Interglobe Aviation Ltd. (Indigo)", "Sector": "Airlines"},
    "INTLCONV.NS": {"Name": "International Conveyors Ltd.", "Sector": "Capital Goods - Engineering"},
    "IRB.NS": {"Name": "IRB Infrastructure Developers Ltd", "Sector": "Construction & Infrastructure"},
    "IRIS.NS": {"Name": "Iris Business Services Ltd.", "Sector": "IT Services - Cloud"},
    "ITCHOTELS.NS": {"Name": "ITC Hotels", "Sector": "Hospitality"},
    "ITC.NS": {"Name": "ITC Ltd", "Sector": "FMCG - Cigarettes & FMCG"},
    "JAGATJITIND.BO": {"Name": "Jagatjit Industries Ltd.", "Sector": "FMCG - Alcoholic Beverages"},
    "JAIBALAJI.NS": {"Name": "Jai Balaji Inds.", "Sector": "Metals - Steel"},
    "JPPOWER.NS": {"Name": "Jaiprakash Power Ventures Ltd.", "Sector": "Power Generation"},
    "JAYKAY.NS": {"Name": "Jaykay Enterprises Ltd.", "Sector": "Defence & Aerospace"},
    "JINDALSAW.NS": {"Name": "Jindal Saw", "Sector": "Metals - Steel Pipes"},
    "JSL.NS": {"Name": "Jindal Stainless Ltd.", "Sector": "Metals - Steel"},
    "JINDALSTEL.NS": {"Name": "Jindal Steel & Power Ltd.", "Sector": "Metals - Steel"},
    "JIOFIN.NS": {"Name": "JIO Financial Services", "Sector": "Financial Services - NBFC/Fintech"},
    "JKLAKSHMI.NS": {"Name": "JK Lakshmi Cem.", "Sector": "Cement"},
    "JKPAPER.NS": {"Name": "JK Paper", "Sector": "Paper"},
    "JKTYRE.NS": {"Name": "JK Tyre & Indust", "Sector": "Auto Ancillaries"},
    "JSWENERGY.NS": {"Name": "JSW Energy", "Sector": "Power Generation & Utilities"},
    "JSWINFRA.NS": {"Name": "JSW Infrastructure", "Sector": "Ports & Logistics"},
    "JSWSTEEL.NS": {"Name": "JSW Steel", "Sector": "Metals - Steel"},
    "JTLIND.NS": {"Name": "JTL Industries Ltd.", "Sector": "Metals - Steel Pipes"},
    "JUBLFOOD.NS": {"Name": "Jubilant FoodWorks Ltd.", "Sector": "Retail - QSR"},
    "JUBLPHARMA.NS": {"Name": "Jubilant Pharmova", "Sector": "Pharmaceuticals"},
    "JWL.NS": {"Name": "Jupiter Wagons", "Sector": "Engineering - Railway Wagons"},
    "KAJARIACER.NS": {"Name": "Kajaria Ceramics", "Sector": "Construction Materials"},
    "KPIL.NS": {"Name": "Kalpataru Projects International Ltd.", "Sector": "Construction & Infrastructure"},
    "KALYANKJIL.NS": {"Name": "Kalyan Jewellers", "Sector": "Retail - Jewellery"},
    "KANSAINER.NS": {"Name": "Kansai Nerolac", "Sector": "Paints & Coatings"},
    "KSCL.NS": {"Name": "Kaveri Seed Co.", "Sector": "Agribusiness"},
    "KAYNES.NS": {"Name": "Kaynes Technology India Ltd", "Sector": "EMS (Electronics Manufacturing)"},
    "KEI.NS": {"Name": "KEI Industries", "Sector": "Capital Goods - Cables & Wires"},
    "KHAICHEM.NS": {"Name": "Khaitan Chemical & Fertilizers Ltd.", "Sector": "Chemicals - Fertilizers"},
    "KLBRENG-B.BO": {"Name": "Kilburn Engineering Ltd.", "Sector": "Capital Goods - Engineering"},
    "KIRLOSENG.NS": {"Name": "Kirloskar Oil Engines", "Sector": "Capital Goods - Engineering"},
    "KOTAKBANK.NS": {"Name": "Kotak Mahindra Bank", "Sector": "Financial Services - Banking"},
    "KPIGREEN.NS": {"Name": "KPI Green Energy Ltd.", "Sector": "Renewable Energy"},
    "KPITTECH.NS": {"Name": "KPIT Technologies Ltd", "Sector": "IT Services - R&D"},
    "KPRMILL.NS": {"Name": "KPR Mill", "Sector": "Textiles - Apparel"},
    "LTF.NS": {"Name": "L&T Fin.Holdings", "Sector": "Financial Services - NBFC"},
    "LTTS.NS": {"Name": "L&T Technology Services Ltd.", "Sector": "IT Services - R&D"},
    "LAOPALA.NS": {"Name": "La Opala RG Ltd", "Sector": "Consumer Durables - Glassware"},
    "LAHOTIOV.BO": {"Name": "Lahoti Overseas Ltd.", "Sector": "Textiles"},
    "LT.NS": {"Name": "Larsen & Toubro Ltd.", "Sector": "Conglomerate - Engineering"},
    "LAURUSLABS.NS": {"Name": "Laurus Labs", "Sector": "Pharmaceuticals - APIs"},
    "LEMONTREE.NS": {"Name": "Lemon Tree Hotel", "Sector": "Hospitality"},
    "LICI.NS": {"Name": "Life Insurance Corporation", "Sector": "Financial Services - Insurance"},
    "LINCOLN.NS": {"Name": "Lincoln Pharma.", "Sector": "Pharmaceuticals"},
    "LLOYDSME.NS": {"Name": "Lloyds Metals & Energy Ltd.", "Sector": "Metals - Steel"},
    "LOTUSCHO.BO": {"Name": "Lotus Developers", "Sector": "Real Estate"},
    "LUMAXTECH.NS": {"Name": "Lumax Auto Tech", "Sector": "Auto Ancillaries"},
    "LUMAXIND.NS": {"Name": "Lumax Industries", "Sector": "Auto Ancillaries"},
    "LUPIN.NS": {"Name": "Lupin", "Sector": "Pharmaceuticals"},
    "LYKALABS.NS": {"Name": "Lyka Labs", "Sector": "Pharmaceuticals"},
    "M&M.NS": {"Name": "M & M (Mahindra & Mahindra Ltd.)", "Sector": "Auto"},
    "MACPOWER.NS": {"Name": "MacPower CNC Machines", "Sector": "Capital Goods"},
    "LODHA.NS": {"Name": "Macrotech Developers Ltd. (Lodha)", "Sector": "Real Estate"},
    "MAFATIND.BO": {"Name": "Mafatlal Industries Ltd", "Sector": "Textiles"},
    "M&MFIN.NS": {"Name": "Mahindra & Mahindra Financial Services Ltd.", "Sector": "Financial Services - NBFC"},
    "MHRIL.NS": {"Name": "Mahindra Holiday", "Sector": "Hospitality"},
    "MAHLOG.NS": {"Name": "Mahindra Logis.", "Sector": "Logistics"},
    "MAITHANALL.NS": {"Name": "Maithan Alloys", "Sector": "Metals - Ferro Alloys"},
    "MANAPPURAM.NS": {"Name": "Manappuram Finance Ltd", "Sector": "Financial Services - NBFC"},
    "MANGALAM.NS": {"Name": "Mangalam Cement Ltd.", "Sector": "Cement"},
    "MANGCHEFER.NS": {"Name": "Mangalore Chemicals & Fertilizers Ltd.", "Sector": "Fertilizers"},
    "MRPL.NS": {"Name": "Mangalore Refinery & Petrochemicals Ltd.", "Sector": "Oil & Gas"},
    "MANKIND.NS": {"Name": "Mankind Pharma", "Sector": "Pharmaceuticals"},
    "MARICO.NS": {"Name": "Marico", "Sector": "FMCG - Consumer Goods"},
    "MARKSANS.NS": {"Name": "Marksans Pharma", "Sector": "Pharmaceuticals"},
    "MAZDOCK.NS": {"Name": "Mazagon Dock Shipbuilders Ltd", "Sector": "Defence - Shipbuilding"},
    "MEGASTAR.NS": {"Name": "Megastar Foods", "Sector": "FMCG - Food Processing"},
    "MICEL.NS": {"Name": "MIC Electronics", "Sector": "Electrical Equipment"},
    "MINDACORP.NS": {"Name": "Minda Corp", "Sector": "Auto Ancillaries"},
    "MINDSPACE.NS": {"Name": "Mindspace Business Parks REIT", "Sector": "Real Estate - REIT"},
    "MIDHANI.NS": {"Name": "Mishra Dhatu Nigam Ltd.", "Sector": "Defence - Metals - Specialty Alloys"},
    "MOSCHIP.NS": {"Name": "MosChip Technologies Ltd", "Sector": "Semiconductor"},
    "MSUMI.NS": {"Name": "Motherson Sumi Wiring India Ltd", "Sector": "Auto Ancillaries"},
    "MOTILALOFS.NS": {"Name": "Motilal Oswal Financial Services", "Sector": "Financial Services - Stockbroking"},
    "BECTORFOOD.NS": {"Name": "Mrs. Bectors Food Specialities Ltd.", "Sector": "FMCG - Food Processing"},
    "MTARTECH.NS": {"Name": "MTAR Technologies Ltd", "Sector": "Defence & Aerospace"},
    "MCX.NS": {"Name": "Multi Commodity Exchange (MCX)", "Sector": "Financial Services - Exchange"},
    "MUTHOOTFIN.NS": {"Name": "Muthoot Finance", "Sector": "Financial Services - NBFC"},
    "NDL.NS": {"Name": "Nandan Denim", "Sector": "Textiles"},
    "NATIONALUM.NS": {"Name": "National Aluminium Company", "Sector": "Metals - Non-ferrous"},
    "NFL.NS": {"Name": "National Fertilizers Ltd.", "Sector": "Fertilizers"},
    "NAVINFLUOR.NS": {"Name": "Navin Fluorine International Ltd.", "Sector": "Chemicals - Specialty"},
    "NCC.NS": {"Name": "NCC Ltd", "Sector": "Construction"},
    "NCLIND.NS": {"Name": "NCL Industries", "Sector": "Cement"},
    "NETWEB.NS": {"Name": "Netweb Technologies India Ltd.", "Sector": "IT Services - Hardware"},
    "NEULANDLAB.NS": {"Name": "Neuland Labs.", "Sector": "Pharmaceuticals - APIs"},
    "NEWGEN.NS": {"Name": "Newgen Software", "Sector": "IT Services - Products"},
    "NHPC.NS": {"Name": "NHPC Ltd", "Sector": "Power Generation"},
    "NAM-INDIA.NS": {"Name": "Nippon Life India Asset Management", "Sector": "Financial Services - AMC"},
    "NMDC.NS": {"Name": "NMDC", "Sector": "Mining"},
    "NTPC.NS": {"Name": "NTPC Ltd", "Sector": "Power Generation"},
    "OBEROIRLTY.NS": {"Name": "Oberoi Realty", "Sector": "Real Estate"},
    "OMAXAUTO.NS": {"Name": "Omax Autos", "Sector": "Auto Ancillaries"},
    "PAYTM.NS": {"Name": "One 97 Communications (Paytm)", "Sector": "Financial Services - Fintech"},
    "ONGC.NS": {"Name": "ONGC", "Sector": "Oil & Gas"},
    "ORBITEXP.BO": {"Name": "Orbit Exports", "Sector": "Textiles"},
    "ORCHPHARMA.NS": {"Name": "Orchid Pharma", "Sector": "Pharmaceuticals"},
    "ORIENTELEC.NS": {"Name": "Orient Electric", "Sector": "Consumer Durables - Electrical Equipment"},
    "GREENPOWER.NS": {"Name": "Orient Green Power Company Ltd.", "Sector": "Renewable Energy"},
    "ORIENTTECH.NS": {"Name": "Orient Technologies Ltd.", "Sector": "IT Services"},
    "PNGJL.NS": {"Name": "P N Gadgil Jewellers", "Sector": "Retail - Jewellery"},
    "PARAS.NS": {"Name": "Paras Defence and Space Technologies Ltd.", "Sector": "Defence & Aerospace"},
    "PATELENG.NS": {"Name": "Patel Engineering Ltd.", "Sector": "Construction & Infrastructure"},
    "PERSISTENT.NS": {"Name": "Persistent.", "Sector": "IT Services"},
    "POLICYBZR.NS": {"Name": "PB Fintech Limited (Policybazaar)", "Sector": "Financial Services - Fintech"},
    "PETRONET.NS": {"Name": "Petronet LNG", "Sector": "Oil & Gas"},
    "PGEL.NS": {"Name": "PG Electroplast", "Sector": "EMS (Electronics Manufacturing)"},
    "PHOENIXLTD.NS": {"Name": "Phoenix Mills", "Sector": "Real Estate - Retail"},
    "PIDILITIND.NS": {"Name": "Pidilite Inds.", "Sector": "Chemicals - Specialty"},
    "PPLPHARMA.NS": {"Name": "Piramal Pharma Ltd.", "Sector": "Pharmaceuticals"},
    "PNCINFRA.NS": {"Name": "PNC Infratech", "Sector": "Construction & Infrastructure"},
    "POLYCAB.NS": {"Name": "Polycab India", "Sector": "Capital Goods - Cables & Wires"},
    "POONAWALLA.NS": {"Name": "Poonawalla Fincorp Ltd.", "Sector": "Financial Services - NBFC"},
    "PFC.NS": {"Name": "Power Finance Corporation Ltd.", "Sector": "Financial Services - NBFC"},
    "POWERGRID.NS": {"Name": "PowerGrid Corp", "Sector": "Power Transmission & Distribution"},
    "PRAJIND.NS": {"Name": "Praj Industries Ltd.", "Sector": "Capital Goods - Engineering"},
    "PRAKASH.NS": {"Name": "Prakash Industri", "Sector": "Metals - Steel"},
    "PRAKASHSTL.NS": {"Name": "Prakash Steelage", "Sector": "Metals - Steel Pipes"},
    "PREMIERENE.NS": {"Name": "Premier Energies Ltd", "Sector": "Renewable Energy"},
    "PRESTIGE.NS": {"Name": "Prestige Estates Projects Ltd.", "Sector": "Real Estate"},
    "PRICOLLTD.NS": {"Name": "Pricol Ltd", "Sector": "Auto Ancillaries"},
    "PRINCEPIPE.NS": {"Name": "Prince Pipes", "Sector": "Plastics & Pipes"},
    "PNB.NS": {"Name": "Punjab National Bank", "Sector": "Financial Services - Banking"},
    "PURVA.NS": {"Name": "Purvankara Ltd", "Sector": "Real Estate"},
    "PVRINOX.NS": {"Name": "PVR Inox Ltd", "Sector": "Retail - Multiplexes"},
    "PVVINFRA.BO": {"Name": "PVV Infra Ltd.", "Sector": "Construction & Infrastructure"},
    "RADICO.NS": {"Name": "Radico Khaitan", "Sector": "FMCG - Alcoholic Beverages"},
    "RVNL.NS": {"Name": "Rail Vikas Nigam Limited", "Sector": "Construction - Railway"},
    "RAILTEL.NS": {"Name": "Railtel Corpn. Of India Ltd.", "Sector": "Telecommunications - IT"},
    "RAIN.BO": {"Name": "Rain Industries", "Sector": "Chemicals"},
    "RAJSREESUG.NS": {"Name": "Rajshree Sugars & Chemicals Ltd.", "Sector": "Sugar"},
    "RKFORGE.NS": {"Name": "Ramkrishna Forg.", "Sector": "Auto Ancillaries"},
    "RATEGAIN.NS": {"Name": "Rategain Travel Technologies Ltd.", "Sector": "IT Services - Travel Tech"},
    "RATNAMANI.NS": {"Name": "Ratnamani Metals & Tubes Ltd.", "Sector": "Metals - Steel Pipes"},
    "RTNINDIA.NS": {"Name": "RattanIndia Ent", "Sector": "Conglomerate"},
    "RTNPOWER.NS": {"Name": "RattanIndia Pow.", "Sector": "Power Generation"},
    "RAYMONDLSL.NS": {"Name": "Raymond Lifestyle", "Sector": "Retail - Apparel"},
    "RAYMOND.NS": {"Name": "Raymond Ltd", "Sector": "Textiles - Apparel"},
    "RBLBANK.NS": {"Name": "RBL Bank Ltd.", "Sector": "Financial Services - Banking"},
    "RECLTD.NS": {"Name": "REC Ltd.", "Sector": "Financial Services - NBFC"},
    "REDINGTON.NS": {"Name": "Redington India", "Sector": "IT Distribution"},
    "REFEX.NS": {"Name": "Refex Industries", "Sector": "Chemicals - Specialty"},
    "RELIANCE.NS": {"Name": "Reliance Industries Ltd.", "Sector": "Conglomerate - Oil & Gas"},
    "RELINFRA.NS": {"Name": "Reliance Infra.", "Sector": "Infrastructure - Power"},
    "RPOWER.NS": {"Name": "Reliance Power", "Sector": "Power Generation"},
    "REPCOHOME.NS": {"Name": "Repco Home Finance", "Sector": "Financial Services - Housing Finance"},
    "RBA.NS": {"Name": "Restaurant Brands Asia Ltd.", "Sector": "Retail - QSR"},
    "RIR.BO": {"Name": "RIR Power Electronics Ltd", "Sector": "Semiconductor"},
    "ROSSARI.NS": {"Name": "Rossari Biotech", "Sector": "Chemicals - Specialty"},
    "ROHLTD.NS": {"Name": "Royal Orch. Hotel", "Sector": "Hospitality"},
    "RPPINFRA.NS": {"Name": "RPP Infra Projects Ltd.", "Sector": "Construction & Infrastructure"},
    "RRP.BO": {"Name": "RRP Semiconductor Ltd", "Sector": "Semiconductor"},
    "RUCHIRA.NS": {"Name": "Ruchira Papers", "Sector": "Paper"},
    "RUSHIL.NS": {"Name": "Rushil Decor", "Sector": "Wood & Wood Products"},
    "SHK.NS": {"Name": "S H Kelkar & Co.", "Sector": "Chemicals - Specialty"},
    "SPAL.NS": {"Name": "S P Apparels", "Sector": "Textiles - Apparel"},
    "SAGCEM.NS": {"Name": "Sagar Cements", "Sector": "Cement"},
    "SAGILITY.NS": {"Name": "Sagility India", "Sector": "IT Services"},
    "KALAMANDIR.NS": {"Name": "Sai Silk (Kalamandir)", "Sector": "Retail - Apparel"},
    "SAMMAANCAP.NS": {"Name": "Sammaan Capital", "Sector": "Financial Services - NBFC/Fintech"},
    "MOTHERSON.NS": {"Name": "Samvardhana Motherson International Ltd", "Sector": "Auto Ancillaries"},
    "SANSERA.NS": {"Name": "Sansera Engineering Ltd.", "Sector": "Auto Ancillaries"},
    "SAPPHIRE.NS": {"Name": "Sapphire Food", "Sector": "Retail - QSR"},
    "SBILIFE.NS": {"Name": "SBI Life Insurance Co Limited", "Sector": "Financial Services - Insurance"},
    "SCHNEIDER.NS": {"Name": "Schneider Electric Infrastructure Ltd.", "Sector": "Electrical Equipment"},
    "SERVOTECH.NS": {"Name": "Servotech Power Systems Ltd", "Sector": "Electrical Equipment"},
    "SGFIN.NS": {"Name": "SG Finserve Ltd.", "Sector": "Financial Services - NBFC"},
    "SGMART.NS": {"Name": "SG Mart Ltd.", "Sector": "Trading"},
    "SHAKTIPUMP.NS": {"Name": "Shakti Pumps", "Sector": "Capital Goods"},
    "SHARDAISPT.BO": {"Name": "Sharda Ispat", "Sector": "Metals - Steel"},
    "SCI.NS": {"Name": "Shipping Corporation Of India", "Sector": "Shipping"},
    "SHOPERSTOP.NS": {"Name": "Shoppers Stop", "Sector": "Retail - Departmental Store"},
    "SHRIRAMFIN.NS": {"Name": "Shriram Finance", "Sector": "Financial Services - NBFC"},
    "SHRIRAMPPS.NS": {"Name": "Shriram Properties", "Sector": "Real Estate"},
    "SHYAMMETL.NS": {"Name": "Shyam Metalics", "Sector": "Metals - Steel"},
    "SJS.NS": {"Name": "SJS Enterprises Ltd.", "Sector": "Auto Ancillaries"},
    "SJVN.NS": {"Name": "SJVN Ltd.", "Sector": "Power Generation"},
    "SKYGOLD.NS": {"Name": "Sky Gold Limited", "Sector": "Retail - Jewellery"},
    "SOBHA.NS": {"Name": "Sobha Ltd", "Sector": "Real Estate"},
    "SOLARINDS.NS": {"Name": "Solar Industries India Ltd", "Sector": "Defence - Explosives"},
    "SOLEX.NS": {"Name": "Solex Energy Ltd", "Sector": "Renewable Energy"},
    "SDBL.NS": {"Name": "Som Distilleries", "Sector": "FMCG - Alcoholic Beverages"},
    "SOMANYCERA.NS": {"Name": "Somany Ceramics", "Sector": "Construction Materials"},
    "SOMICONVEY.NS": {"Name": "Somi Conveyor Beltings", "Sector": "Industrial Products"},
    "SONACOMS.NS": {"Name": "Sona BLW Precision Forgings Ltd.", "Sector": "Auto Ancillaries"},
    "SPELS.BO": {"Name": "SPEL Semiconductor Ltd", "Sector": "Semiconductor"},
    "SPICEJET.BO": {"Name": "Spicejet Ltd.", "Sector": "Airlines"},
    "SBIN.NS": {"Name": "State Bank of India", "Sector": "Financial Services - Banking"},
    "SAIL.NS": {"Name": "Steel Authority of India", "Sector": "Metals - Steel"},
    "STEELXIND.NS": {"Name": "Steel Exchange", "Sector": "Metals - Steel"},
    "SSWL.NS": {"Name": "Steel Str. Wheel", "Sector": "Auto Ancillaries"},
    "SWSOLAR.NS": {"Name": "Sterling and Wilson Renewable Energy Ltd", "Sector": "Renewable Energy - EPC"},
    "STLTECH.NS": {"Name": "Sterlite Technologies Ltd.", "Sector": "Telecommunications"},
    "STYLAMIND.NS": {"Name": "Stylam Industries", "Sector": "Wood & Wood Products"},
    "STYRENIX.NS": {"Name": "Styrenix Performance Material", "Sector": "Chemicals - Polymers"},
    "SUDARSCHEM.NS": {"Name": "Sudarshan Chemicals", "Sector": "Chemicals - Specialty"},
    "SULA.NS": {"Name": "Sula Vineyards", "Sector": "FMCG - Alcoholic Beverages"},
    "SUNPHARMA.NS": {"Name": "Sun Pharma. Inds.", "Sector": "Pharmaceuticals"},
    "SUNTV.NS": {"Name": "SUN TV Network", "Sector": "Media & Entertainment"},
    "SUNTECK.NS": {"Name": "Sunteck Reality", "Sector": "Real Estate"},
    "SUPREMEIND.NS": {"Name": "Supreme Industries Ltd.", "Sector": "Plastics & Pipes"},
    "SURAJEST.NS": {"Name": "Suraj Estate Developers", "Sector": "Real Estate"},
    "SURAJLTD.NS": {"Name": "Suraj Products Ltd.", "Sector": "Metals - Steel"},
    "SURANASOL.NS": {"Name": "Surana Solar", "Sector": "Renewable Energy"},
    "SURYODAY.NS": {"Name": "Suryoday Small Finance Bank Ltd.", "Sector": "Financial Services - Banking"},
    "SUVEN.NS": {"Name": "Suven Life Scie.", "Sector": "Pharmaceuticals"},
    "SUZLON.NS": {"Name": "Suzlon Energy", "Sector": "Renewable Energy"},
    "SWIGGY.NS": {"Name": "Swiggy", "Sector": "Retail - E-commerce/Food Delivery"},
    "SYRMA.NS": {"Name": "Syrma SGS Technology Ltd.", "Sector": "EMS (Electronics Manufacturing)"},
    "TALBROAUTO.NS": {"Name": "Talbros Automotive", "Sector": "Auto Ancillaries"},
    "TANFACIND.BO": {"Name": "Tanfac Industries Ltd.", "Sector": "Chemicals - Specialty"},
    "TARSONS.NS": {"Name": "Tarson Products Limited", "Sector": "Industrial Products"},
    "TATACHEM.NS": {"Name": "Tata Chemicals", "Sector": "Chemicals - Fertilizers"},
    "TATACOMM.NS": {"Name": "Tata Communications Ltd.", "Sector": "Telecommunications - Data Services"},
    "TCS.NS": {"Name": "Tata Consultancy Services Ltd.", "Sector": "IT Services"},
    "TATACONSUM.NS": {"Name": "Tata Consumer Products", "Sector": "FMCG - Food & Beverages"},
    "TATAELXSI.NS": {"Name": "Tata Elxsi Ltd.", "Sector": "IT Services - R&D Design"},
    "TATAINVEST.NS": {"Name": "Tata Investment Corporation Ltd", "Sector": "Financial Services - Investment"},
    "TATASTEEL.NS": {"Name": "Tata Steel", "Sector": "Metals - Steel"},
    "TMCV.NS": {"Name": "Tata Motors Commercial Vehicle Ltd.", "Sector": "Auto"},
    "TMPV.NS": {"Name": "Tata Motors Passenger Vehicle Ltd.", "Sector": "Auto"},
    "TATAPOWER.NS": {"Name": "Tata Power Co.", "Sector": "Power Generation & Utilities"},
    "TATATECH.NS": {"Name": "Tata Technologies Ltd.", "Sector": "IT Services - R&D"},
    "TCPLPACK.NS": {"Name": "TCPL Packaging", "Sector": "Packaging"},
    "TDPOWERSYS.NS": {"Name": "TD Power Systems Ltd.", "Sector": "Electrical Equipment"},
    "TECHM.NS": {"Name": "Tech Mahindra", "Sector": "IT Services"},
    "TECHNOE.NS": {"Name": "Techno Electric & Engineering Company", "Sector": "Construction & Infrastructure"},
    "TEJASNET.NS": {"Name": "Tejas Networks", "Sector": "Telecommunications - Equipment"},
    "THANGAMAYL.NS": {"Name": "Thangamayil Jewellery Ltd", "Sector": "Retail - Jewellery"},
    "THOMASCOOK.NS": {"Name": "Thomas Cook (I)", "Sector": "Travel Services"},
    "TI.NS": {"Name": "Tilaknagar Industries", "Sector": "FMCG - Alcoholic Beverages"},
    "TIMETECHNO.NS": {"Name": "Time Technoplast", "Sector": "Plastics & Packaging"},
    "TITAGARH.NS": {"Name": "Titagarh Railsystems Ltd.", "Sector": "Engineering - Railway Wagons"},
    "TITAN.NS": {"Name": "Titan Company", "Sector": "Consumer Durables - Jewellery/Watches"},
    "TARIL.BO": {"Name": "Transformers and Rectifiers (India) Ltd", "Sector": "Electrical Equipment"},
    "TRANSWIND.NS": {"Name": "Transwind Infrastructures Ltd.", "Sector": "Construction & Infrastructure"},
    "TRENT.NS": {"Name": "Trent Ltd", "Sector": "Retail - Apparel"},
    "TRIDENT.NS": {"Name": "Trident Ltd", "Sector": "Textiles"},
    "TRITURBINE.NS": {"Name": "Triveni Turbine", "Sector": "Capital Goods - Engineering"},
    "TVSELECT.NS": {"Name": "TVS Elec.", "Sector": "Auto Ancillaries"},
    "TVSMOTOR.NS": {"Name": "TVS Motor Company Ltd.", "Sector": "Auto"},
    "ULTRAMAR.BO": {"Name": "UltraMarines and Pigments", "Sector": "Chemicals - Specialty"},
    "ULTRACEMCO.NS": {"Name": "Ultratech Cement", "Sector": "Cement"},
    "UNITECH.NS": {"Name": "Unitech Ltd", "Sector": "Real Estate"},
    "UBL.NS": {"Name": "United Breweries", "Sector": "FMCG - Alcoholic Beverages"},
    "UNITDSPR.NS": {"Name": "United Spirits", "Sector": "FMCG - Alcoholic Beverages"},
    "UNOMINDA.NS": {"Name": "UNO Minda Ltd.", "Sector": "Auto Ancillaries"},
    "VGUARD.NS": {"Name": "V-Guard Indust", "Sector": "Consumer Durables - Electrical Equipment"},
    "WABAG.NS": {"Name": "VA Tech Wabag", "Sector": "Water Management"},
    "VAIBHAVGBL.NS": {"Name": "Vaibhav Global Ltd.", "Sector": "Retail - E-commerce/Jewellery"},
    "DBREALTY.NS": {"Name": "Valor Estate Ltd. (DB Realty)", "Sector": "Real Estate"},
    "VARDHACRLC.NS": {"Name": "Vardhman Acrylic Fibres Ltd.", "Sector": "Textiles"},
    "VTL.NS": {"Name": "Vardhman Textile", "Sector": "Textiles"},
    "VBL.NS": {"Name": "Varun Beverages Ltd.", "Sector": "FMCG - Food & Beverages"},
    "VASWANI.NS": {"Name": "Vaswani Industries", "Sector": "Textiles"},
    "MANYAVAR.NS": {"Name": "Vedant Fashions (Manyavar)", "Sector": "Retail - Apparel"},
    "VEDL.NS": {"Name": "Vedanta Ltd", "Sector": "Metals - Diversified"},
    "VEEDOL.NS": {"Name": "Veedol Corporation Ltd", "Sector": "Retail"},
    "VENUSPIPES.NS": {"Name": "Venus Pipes & Tubes Ltd.", "Sector": "Metals - Steel Pipes"},
    "VILAS.NS": {"Name": "Vilas Transcore Ltd.", "Sector": "Capital Goods"},
    "VINATIORGA.NS": {"Name": "Vinati Organics", "Sector": "Chemicals - Specialty"},
    "VISHNU.NS": {"Name": "Vishnu Chemicals", "Sector": "Chemicals - Specialty"},
    "VMS.BO": {"Name": "VMS Industries", "Sector": "Logistics - Shipping"},
    "IDEA.NS": {"Name": "Vodafone Idea Ltd.", "Sector": "Telecommunications"},
    "VRLLOG.NS": {"Name": "VRL Logistics", "Sector": "Logistics"},
    "WAA.BO": {"Name": "Waa Solar Ltd.", "Sector": "Renewable Energy"},
    "WAAREEENER.NS": {"Name": "Waaree Energies Ltd", "Sector": "Renewable Energy"},
    "WEBELSOLAR.NS": {"Name": "Waaree Renewable Technologies Ltd.", "Sector": "Renewable Energy - EPC"},
    "WARDFIN.BO": {"Name": "Wardwizard Foods and Beverages Ltd.", "Sector": "FMCG - Food & Beverages"},
    "WELCORP.NS": {"Name": "Welspun Corp Ltd", "Sector": "Metals - Steel Pipes"},
    "WELENT.NS": {"Name": "Welspun Enterprises Ltd.", "Sector": "Construction & Infrastructure"},
    "WELSPUNLIV.NS": {"Name": "Welspun Living Ltd.", "Sector": "Textiles - Home Textiles"},
    "WIPRO.NS": {"Name": "Wipro", "Sector": "IT Services"},
    "YESBANK.NS": {"Name": "Yes Bank", "Sector": "Financial Services - Banking"},
    "YUKEN.NS": {"Name": "Yuken India", "Sector": "Auto Ancillaries"},
    "ZEEL.NS": {"Name": "Zee Entertainmen", "Sector": "Media & Entertainment"},
    "ZENTEC.NS": {"Name": "Zen Technologies Ltd", "Sector": "Defence & Aerospace"},
    "ZUARI.NS": {"Name": "Zuari Agro Chemicals Ltd.", "Sector": "Fertilizers"},
    "ZYDUSWELL.NS": {"Name": "Zydus Wellness", "Sector": "FMCG - Health & Wellness"}
}
